/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package backend-haskell-0.1.0.0 */
#ifndef VERSION_backend_haskell
#define VERSION_backend_haskell "0.1.0.0"
#endif /* VERSION_backend_haskell */
#ifndef MIN_VERSION_backend_haskell
#define MIN_VERSION_backend_haskell(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_backend_haskell */
/* package aeson-2.2.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package base-4.20.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.20.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  20 || \
  (major1) == 4 && (major2) == 20 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package containers-0.7 */
#ifndef VERSION_containers
#define VERSION_containers "0.7"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_containers */
/* package monad-logger-0.3.42 */
#ifndef VERSION_monad_logger
#define VERSION_monad_logger "0.3.42"
#endif /* VERSION_monad_logger */
#ifndef MIN_VERSION_monad_logger
#define MIN_VERSION_monad_logger(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 42)
#endif /* MIN_VERSION_monad_logger */
/* package mtl-2.3.1 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.3.1"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_mtl */
/* package persistent-2.17.1.0 */
#ifndef VERSION_persistent
#define VERSION_persistent "2.17.1.0"
#endif /* VERSION_persistent */
#ifndef MIN_VERSION_persistent
#define MIN_VERSION_persistent(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  17 || \
  (major1) == 2 && (major2) == 17 && (minor) <= 1)
#endif /* MIN_VERSION_persistent */
/* package persistent-sqlite-2.13.3.1 */
#ifndef VERSION_persistent_sqlite
#define VERSION_persistent_sqlite "2.13.3.1"
#endif /* VERSION_persistent_sqlite */
#ifndef MIN_VERSION_persistent_sqlite
#define MIN_VERSION_persistent_sqlite(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  13 || \
  (major1) == 2 && (major2) == 13 && (minor) <= 3)
#endif /* MIN_VERSION_persistent_sqlite */
/* package persistent-template-2.12.0.0 */
#ifndef VERSION_persistent_template
#define VERSION_persistent_template "2.12.0.0"
#endif /* VERSION_persistent_template */
#ifndef MIN_VERSION_persistent_template
#define MIN_VERSION_persistent_template(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  12 || \
  (major1) == 2 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_persistent_template */
/* package stm-2.5.3.1 */
#ifndef VERSION_stm
#define VERSION_stm "2.5.3.1"
#endif /* VERSION_stm */
#ifndef MIN_VERSION_stm
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 3)
#endif /* MIN_VERSION_stm */
/* package text-2.1.3 */
#ifndef VERSION_text
#define VERSION_text "2.1.3"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_text */
/* package time-1.12.2 */
#ifndef VERSION_time
#define VERSION_time "1.12.2"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  12 || \
  (major1) == 1 && (major2) == 12 && (minor) <= 2)
#endif /* MIN_VERSION_time */
/* package wai-3.2.4 */
#ifndef VERSION_wai
#define VERSION_wai "3.2.4"
#endif /* VERSION_wai */
#ifndef MIN_VERSION_wai
#define MIN_VERSION_wai(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_wai */
/* package wai-websockets-3.0.1.2 */
#ifndef VERSION_wai_websockets
#define VERSION_wai_websockets "3.0.1.2"
#endif /* VERSION_wai_websockets */
#ifndef MIN_VERSION_wai_websockets
#define MIN_VERSION_wai_websockets(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  0 || \
  (major1) == 3 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_wai_websockets */
/* package warp-3.4.9 */
#ifndef VERSION_warp
#define VERSION_warp "3.4.9"
#endif /* VERSION_warp */
#ifndef MIN_VERSION_warp
#define MIN_VERSION_warp(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  4 || \
  (major1) == 3 && (major2) == 4 && (minor) <= 9)
#endif /* MIN_VERSION_warp */
/* package websockets-0.13.0.0 */
#ifndef VERSION_websockets
#define VERSION_websockets "0.13.0.0"
#endif /* VERSION_websockets */
#ifndef MIN_VERSION_websockets
#define MIN_VERSION_websockets(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 0)
#endif /* MIN_VERSION_websockets */

/* tool gcc-14.0.6 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.6"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 6)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.31.1 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.31.1"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  31 || \
  (major1) == 2 && (major2) == 31 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.69 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.69"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  69 || \
  (major1) == 0 && (major2) == 69 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.10 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.10"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 10)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool runghc-9.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "backend-haskell-0.1.0.0-HMuOKbRTuPuKiC7dj2N54J"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "backend-haskell-0.1.0.0-HMuOKbRTuPuKiC7dj2N54J"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package backend-haskell-0.1.0.0 */
#ifndef VERSION_backend_haskell
#define VERSION_backend_haskell "0.1.0.0"
#endif /* VERSION_backend_haskell */
#ifndef MIN_VERSION_backend_haskell
#define MIN_VERSION_backend_haskell(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_backend_haskell */
/* package aeson-2.2.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package backend-haskell-0.1.0.0 */
#ifndef VERSION_backend_haskell
#define VERSION_backend_haskell "0.1.0.0"
#endif /* VERSION_backend_haskell */
#ifndef MIN_VERSION_backend_haskell
#define MIN_VERSION_backend_haskell(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_backend_haskell */
/* package base-4.20.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.20.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  20 || \
  (major1) == 4 && (major2) == 20 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package containers-0.7 */
#ifndef VERSION_containers
#define VERSION_containers "0.7"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_containers */
/* package monad-logger-0.3.42 */
#ifndef VERSION_monad_logger
#define VERSION_monad_logger "0.3.42"
#endif /* VERSION_monad_logger */
#ifndef MIN_VERSION_monad_logger
#define MIN_VERSION_monad_logger(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 42)
#endif /* MIN_VERSION_monad_logger */
/* package mtl-2.3.1 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.3.1"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_mtl */
/* package persistent-2.17.1.0 */
#ifndef VERSION_persistent
#define VERSION_persistent "2.17.1.0"
#endif /* VERSION_persistent */
#ifndef MIN_VERSION_persistent
#define MIN_VERSION_persistent(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  17 || \
  (major1) == 2 && (major2) == 17 && (minor) <= 1)
#endif /* MIN_VERSION_persistent */
/* package persistent-sqlite-2.13.3.1 */
#ifndef VERSION_persistent_sqlite
#define VERSION_persistent_sqlite "2.13.3.1"
#endif /* VERSION_persistent_sqlite */
#ifndef MIN_VERSION_persistent_sqlite
#define MIN_VERSION_persistent_sqlite(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  13 || \
  (major1) == 2 && (major2) == 13 && (minor) <= 3)
#endif /* MIN_VERSION_persistent_sqlite */
/* package persistent-template-2.12.0.0 */
#ifndef VERSION_persistent_template
#define VERSION_persistent_template "2.12.0.0"
#endif /* VERSION_persistent_template */
#ifndef MIN_VERSION_persistent_template
#define MIN_VERSION_persistent_template(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  12 || \
  (major1) == 2 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_persistent_template */
/* package stm-2.5.3.1 */
#ifndef VERSION_stm
#define VERSION_stm "2.5.3.1"
#endif /* VERSION_stm */
#ifndef MIN_VERSION_stm
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 3)
#endif /* MIN_VERSION_stm */
/* package text-2.1.3 */
#ifndef VERSION_text
#define VERSION_text "2.1.3"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_text */
/* package time-1.12.2 */
#ifndef VERSION_time
#define VERSION_time "1.12.2"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  12 || \
  (major1) == 1 && (major2) == 12 && (minor) <= 2)
#endif /* MIN_VERSION_time */
/* package wai-3.2.4 */
#ifndef VERSION_wai
#define VERSION_wai "3.2.4"
#endif /* VERSION_wai */
#ifndef MIN_VERSION_wai
#define MIN_VERSION_wai(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_wai */
/* package wai-websockets-3.0.1.2 */
#ifndef VERSION_wai_websockets
#define VERSION_wai_websockets "3.0.1.2"
#endif /* VERSION_wai_websockets */
#ifndef MIN_VERSION_wai_websockets
#define MIN_VERSION_wai_websockets(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  0 || \
  (major1) == 3 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_wai_websockets */
/* package warp-3.4.9 */
#ifndef VERSION_warp
#define VERSION_warp "3.4.9"
#endif /* VERSION_warp */
#ifndef MIN_VERSION_warp
#define MIN_VERSION_warp(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  4 || \
  (major1) == 3 && (major2) == 4 && (minor) <= 9)
#endif /* MIN_VERSION_warp */
/* package websockets-0.13.0.0 */
#ifndef VERSION_websockets
#define VERSION_websockets "0.13.0.0"
#endif /* VERSION_websockets */
#ifndef MIN_VERSION_websockets
#define MIN_VERSION_websockets(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 0)
#endif /* MIN_VERSION_websockets */

/* tool gcc-14.0.6 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.6"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 6)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.31.1 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.31.1"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  31 || \
  (major1) == 2 && (major2) == 31 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.69 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.69"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  69 || \
  (major1) == 0 && (major2) == 69 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.10 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.10"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 10)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool runghc-9.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "backend-haskell-0.1.0.0-GFgG0sFose57ze9GufqItn-backend-haskell-exe"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
